In [11]:
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import yfinance as yf
import io, base64, os, json, re 
import pandas as pd
import numpy as np
import datetime
import json
import requests
from urllib.request import urlopen
from random import randint

In [18]:
df = pd.read_csv('AAPL_1hr.csv')
df.tail(3)

,Unnamed: 0,date,open,low,high,close,volume
197,197,2020-11-13 15:00:00,118.6950,118.205,118.8899,118.8850,58545638
198,198,2020-11-13 14:00:00,118.9466,118.500,119.2250,118.5700,51025438
199,199,2020-11-13 13:00:00,118.9493,118.820,118.9493,118.9466,43274698

In [19]:
df.drop ('Unnamed: 0', axis=1, inplace=True)

In [20]:
df.tail(1)

                    date      open     low      high     close    volume
199  2020-11-13 13:00:00  118.9493  118.82  118.9493  118.9466  43274698

In [21]:
df['date'] = df['date'].str.slice(0, -9, 1)

In [22]:
df.head(3)

         date      open     low      high   close    volume
0  2020-12-24  131.9700  131.97  131.9700  131.97  54213606
1  2020-12-24  131.9700  131.97  131.9700  131.97  54213606
2  2020-12-24  132.0059  131.97  132.0059  131.97  54213606

	Open	High	Low	Close	Adj Close	Volume	Date

In [23]:
df['Date'] = df['date']
df['Open'] = df['open']
df['High'] = df['high']
df['Low'] = df['low']
df['Close'] = df['close']
df['Adj Close'] = df['close']
df['Volume'] = df['volume']
df.drop ('date', axis=1, inplace=True)
df.drop ('open', axis=1, inplace=True)
df.drop ('high', axis=1, inplace=True)
df.drop ('low', axis=1, inplace=True)
df.drop ('close', axis=1, inplace=True)
df.drop ('volume', axis=1, inplace=True)
df.head(2)

         Date    Open    High     Low   Close  Adj Close    Volume
0  2020-12-24  131.97  131.97  131.97  131.97     131.97  54213606
1  2020-12-24  131.97  131.97  131.97  131.97     131.97  54213606

In [24]:
csv_data = df.to_csv('AAPL_1hr_EDITED.csv', index = True)

## Perform 2. operation here

In [25]:
new_set = []
for row_set in range(0, 1000000):
    if row_set%2000==0: print(row_set)
    row_quant = randint(10, 30)
    row_start = randint(0, len(df)-row_quant)
    market_subset = df.iloc[row_start:row_start+row_quant]

    Close_Date = max(market_subset['Date'])
    if row_set%2000==0: print(Close_Date)
    
    # Close_Gap = (market_subset['Close'] - market_subset['Close'].shift(1)) / market_subset['Close'].shift(1)
    Close_Gap = market_subset['Close'].pct_change()
    High_Gap = market_subset['High'].pct_change()
    Low_Gap = market_subset['Low'].pct_change() 
    Volume_Gap = market_subset['Volume'].pct_change() 
    Daily_Change = (market_subset['Close'] - market_subset['Open']) / market_subset['Open']
    Outcome_Next_Day_Direction = (market_subset['Volume'].shift(-1) - market_subset['Volume'])
    
    new_set.append(pd.DataFrame({'Sequence_ID':[row_set]*len(market_subset),
                            'Close_Date':[Close_Date]*len(market_subset),
                           'Close_Gap':Close_Gap,
                           'High_Gap':High_Gap,
                           'Low_Gap':Low_Gap,
                           'Volume_Gap':Volume_Gap,
                           'Daily_Change':Daily_Change,
                           'Outcome_Next_Day_Direction':Outcome_Next_Day_Direction}))

0
2020-12-02
2000
2020-12-07
4000
2020-12-02
6000
2020-12-14
8000
2020-12-02
10000
2020-12-24
12000
2020-12-22
14000
2020-12-14
16000
2020-12-18
18000
2020-11-25
20000
2020-11-24
22000
2020-12-18
24000
2020-11-30
26000
2020-12-14
28000
2020-12-10
30000
2020-12-08
32000
2020-12-15
34000
2020-11-23
36000
2020-11-23
38000
2020-11-20
40000
2020-12-04
42000
2020-11-24
44000
2020-12-24
46000
2020-12-23
48000
2020-12-03
50000
2020-12-15
52000
2020-12-04
54000
2020-11-30
56000
2020-11-20
58000
2020-12-10
60000
2020-12-09
62000
2020-12-23
64000
2020-11-24
66000
2020-11-19
68000
2020-12-17
70000
2020-12-07
72000
2020-12-10
74000
2020-12-15
76000
2020-12-01
78000
2020-12-24
80000
2020-12-11
82000
2020-12-24
84000
2020-12-17
86000
2020-11-17
88000
2020-12-08
90000
2020-12-10
92000
2020-12-18
94000
2020-11-27
96000
2020-11-24
98000
2020-12-08
100000
2020-11-30
102000
2020-12-03
104000
2020-12-24
106000
2020-12-01
108000
2020-12-11
110000
2020-11-24
112000
2020-11-18
114000
2020-11-19
116000
2020-12-21
118000
2020-12-17
120000
2020-12-11
122000
2020-12-18
124000
2020-12-14
126000
2020-12-21
128000
2020-12-23
130000
2020-12-09
132000
2020-12-16
134000
2020-12-18
136000
2020-11-17
138000
2020-12-24
140000
2020-12-09
142000
2020-11-24
144000
2020-12-02
146000
2020-12-23
148000
2020-12-11
150000
2020-12-10
152000
2020-12-01
154000
2020-12-18
156000
2020-12-03
158000
2020-12-23
160000
2020-12-01
162000
2020-12-16
164000
2020-12-24
166000
2020-11-20
168000
2020-12-22
170000
2020-11-27
172000
2020-12-15
174000
2020-12-03
176000
2020-12-16
178000
2020-12-07
180000
2020-11-30
182000
2020-12-21
184000
2020-12-15
186000
2020-12-03
188000
2020-12-04
190000
2020-12-17
192000
2020-12-08
194000
2020-12-10
196000
2020-12-17
198000
2020-12-15
200000
2020-12-17
202000
2020-11-24
204000
2020-12-17
206000
2020-12-02
208000
2020-12-17
210000
2020-12-04
212000
2020-12-17
214000
2020-12-10
216000
2020-12-16
218000
2020-12-22
220000
2020-12-22
222000
2020-12-17
224000
2020-12-22
226000
2020-12-18
228000
2020-12-16
230000
2020-11-24
232000
2020-12-21
234000
2020-11-30
236000
2020-11-27
238000
2020-12-02
240000
2020-12-14
242000
2020-12-07
244000
2020-12-22
246000
2020-12-11
248000
2020-12-09
250000
2020-12-08
252000
2020-11-18
254000
2020-11-18
256000
2020-12-03
258000
2020-12-14
260000
2020-12-18
262000
2020-12-14
264000
2020-11-19
266000
2020-12-18
268000
2020-11-27
270000
2020-12-15
272000
2020-11-17
274000
2020-12-08
276000
2020-12-23
278000
2020-12-22
280000
2020-11-30
282000
2020-11-24
284000
2020-12-18
286000
2020-12-23
288000
2020-12-01
290000
2020-12-17
292000
2020-12-07
294000
2020-11-24
296000
2020-11-24
298000
2020-12-16
300000
2020-11-20
302000
2020-12-16
304000
2020-11-20
306000
2020-11-27
308000
2020-11-20
310000
2020-12-22
312000
2020-12-01
314000
2020-12-17
316000
2020-11-23
318000
2020-11-30
320000
2020-12-10
322000
2020-12-21
324000
2020-12-14
326000
2020-12-04
328000
2020-11-30
330000
2020-12-23
332000
2020-12-18
334000
2020-12-15
336000
2020-11-20
338000
2020-11-30
340000
2020-12-10
342000
2020-12-22
344000
2020-12-17
346000
2020-11-18
348000
2020-11-25
350000
2020-11-23
352000
2020-12-10
354000
2020-12-01
356000
2020-12-08
358000
2020-12-03
360000
2020-11-27
362000
2020-12-04
364000
2020-12-04
366000
2020-11-27
368000
2020-12-14
370000
2020-12-15
372000
2020-12-09
374000
2020-11-17
376000
2020-12-02
378000
2020-11-20
380000
2020-12-07
382000
2020-12-23
384000
2020-12-22
386000
2020-12-23
388000
2020-12-21
390000
2020-12-23
392000
2020-11-20
394000
2020-12-03
396000
2020-11-24
398000
2020-12-07
400000
2020-12-03
402000
2020-12-09
404000
2020-12-04
406000
2020-12-24
408000
2020-12-18
410000
2020-11-25
412000
2020-12-22
414000
2020-12-07
416000
2020-12-11
418000
2020-11-27
420000
2020-11-20
422000
2020-12-17
424000
2020-12-24
426000
2020-12-22
428000
2020-11-24
430000
2020-12-21
432000
2020-12-17
434000
2020-11-20
436000
2020-12-15
438000
2020-12-02
440000
2020-11-17
442000
2020-12-15
444000
2020-12-17
446000
2020-12-17
448000
2020-12-23
450000
2020-12-23
452000
2020-12-11
454000
2020-12-17
456000
2020-12-09
458000
2020-11-19
460000
2020-12-11
462000
2020-12-17
464000
2020-11-30
466000
2020-11-24
468000
2020-12-01
470000
2020-12-22
472000
2020-11-24
474000
2020-12-24
476000
2020-12-01
478000
2020-11-24
480000
2020-12-23
482000
2020-11-27
484000
2020-12-11
486000
2020-12-08
488000
2020-11-23
490000
2020-12-11
492000
2020-11-24
494000
2020-12-10
496000
2020-12-23
498000
2020-11-17
500000
2020-11-19
502000
2020-12-07
504000
2020-11-27
506000
2020-11-18
508000
2020-11-30
510000
2020-11-19
512000
2020-12-03
514000
2020-12-08
516000
2020-12-10
518000
2020-12-18
520000
2020-12-01
522000
2020-11-23
524000
2020-12-10
526000
2020-12-02
528000
2020-12-14
530000
2020-11-23
532000
2020-12-07
534000
2020-11-27
536000
2020-12-24
538000
2020-12-10
540000
2020-12-17
542000
2020-12-03
544000
2020-12-22
546000
2020-11-20
548000
2020-12-03
550000
2020-12-16
552000
2020-11-23
554000
2020-12-14
556000
2020-11-25
558000
2020-12-24
560000
2020-11-30
562000
2020-12-11
564000
2020-11-17
566000
2020-11-27
568000
2020-12-21
570000
2020-11-30
572000
2020-12-18
574000
2020-12-23
576000
2020-11-19
578000
2020-12-04
580000
2020-11-19
582000
2020-12-10
584000
2020-12-24
586000
2020-11-19
588000
2020-11-23
590000
2020-12-09
592000
2020-12-17
594000
2020-12-14
596000
2020-12-04
598000
2020-12-17
600000
2020-12-24
602000
2020-11-30
604000
2020-11-30
606000
2020-12-14
608000
2020-12-22
610000
2020-12-02
612000
2020-12-08
614000
2020-12-03
616000
2020-12-07
618000
2020-12-14
620000
2020-12-16
622000
2020-12-07
624000
2020-12-16
626000
2020-12-09
628000
2020-12-01
630000
2020-12-14
632000
2020-12-01
634000
2020-12-17
636000
2020-12-09
638000
2020-12-23
640000
2020-11-24
642000
2020-12-15
644000
2020-12-04
646000
2020-11-23
648000
2020-12-07
650000
2020-11-30
652000
2020-11-25
654000
2020-12-04
656000
2020-12-07
658000
2020-12-07
660000
2020-12-09
662000
2020-12-02
664000
2020-12-02
666000
2020-12-18
668000
2020-12-18
670000
2020-12-18
672000
2020-12-21
674000
2020-12-01
676000
2020-11-20
678000
2020-11-25
680000
2020-11-24
682000
2020-11-25
684000
2020-12-02
686000
2020-12-02
688000
2020-12-11
690000
2020-12-15
692000
2020-12-21
694000
2020-12-11
696000
2020-12-15
698000
2020-12-08
700000
2020-12-04
702000
2020-12-03
704000
2020-11-30
706000
2020-12-14
708000
2020-12-01
710000
2020-11-27
712000
2020-11-19
714000
2020-11-30
716000
2020-11-27
718000
2020-12-21
720000
2020-12-22
722000
2020-12-04
724000
2020-12-09
726000
2020-12-14
728000
2020-11-24
730000
2020-12-22
732000
2020-12-09
734000
2020-12-17
736000
2020-11-30
738000
2020-12-23
740000
2020-12-21
742000
2020-12-02
744000
2020-12-07
746000
2020-12-15
748000
2020-12-01
750000
2020-12-11
752000
2020-12-07
754000
2020-12-14
756000
2020-12-01
758000
2020-11-30
760000
2020-11-27
762000
2020-11-23
764000
2020-11-23
766000
2020-11-19
768000
2020-12-11
770000
2020-12-17
772000
2020-12-01
774000
2020-12-18
776000
2020-12-07
778000
2020-12-04
780000
2020-12-08
782000
2020-12-15
784000
2020-12-18
786000
2020-12-09
788000
2020-11-25
790000
2020-12-07
792000
2020-12-22
794000
2020-12-09
796000
2020-11-20
798000
2020-11-19
800000
2020-12-04
802000
2020-12-08
804000
2020-12-02
806000
2020-11-20
808000
2020-11-23
810000
2020-12-15
812000
2020-11-30
814000
2020-12-15
816000
2020-12-03
818000
2020-12-09
820000
2020-11-20
822000
2020-12-15
824000
2020-11-25
826000
2020-12-08
828000
2020-12-23
830000
2020-12-24
832000
2020-11-30
834000
2020-12-07
836000
2020-11-25
838000
2020-12-09
840000
2020-12-10
842000
2020-11-19
844000
2020-11-24
846000
2020-11-19
848000
2020-12-03
850000
2020-12-16
852000
2020-12-03
854000
2020-11-27
856000
2020-12-02
858000
2020-12-22
860000
2020-12-10
862000
2020-12-17
864000
2020-11-16

MemoryError:

In [26]:
len(market_subset)

16

In [28]:
new_set_df = pd.concat(new_set)
print(new_set_df.shape)
new_set_df = new_set_df.dropna(how='any') 
print(new_set_df.shape)

(17305334, 8)
(15576084, 8)

In [29]:
new_set_df.tail(5)

,Sequence_ID,Close_Date,Close_Gap,High_Gap,Low_Gap,Volume_Gap,Daily_Change,Outcome_Next_Day_Direction
142,864624,2020-11-30,-0.000732,0.001684,0.001279,-0.106142,-0.002108,-5277039.0
143,864624,2020-11-30,0.001681,-0.000005,-0.001535,-0.102740,0.001595,-6432301.0
144,864624,2020-11-30,-0.001592,-0.001902,0.001728,-0.139572,0.000122,-10164782.0
145,864624,2020-11-30,0.004094,0.003499,0.001763,-0.256339,0.002927,-13041984.0
146,864624,2020-11-30,-0.001459,0.000558,-0.007702,-0.442267,0.005185,87103686.0

In [30]:
new_set_df.head()

,Sequence_ID,Close_Date,Close_Gap,High_Gap,Low_Gap,Volume_Gap,Daily_Change,Outcome_Next_Day_Direction
119,0,2020-12-02,0.005410,0.001589,0.009589,5.541484,0.001184,-17159914.0
120,0,2020-12-02,0.000448,0.002319,0.004176,-0.149333,-0.000326,-9771591.0
121,0,2020-12-02,0.000515,0.000609,-0.000162,-0.099965,0.001086,-8794339.0
122,0,2020-12-02,-0.001085,-0.002473,0.000122,-0.099960,-0.002278,-12402942.0
123,0,2020-12-02,0.003792,0.001957,0.001962,-0.156633,0.001790,-17786559.0

In [31]:
new_set_df['Close_Gap_LMH'] = pd.qcut(new_set_df['Close_Gap'], 3, labels=["L", "M", "H"])

# High_Gap - not used in this example
new_set_df['High_Gap_LMH'] = pd.qcut(new_set_df['High_Gap'], 3, labels=["L", "M", "H"])

# Low_Gap - not used in this example
new_set_df['Low_Gap_LMH'] = pd.qcut(new_set_df['Low_Gap'], 3, labels=["L", "M", "H"])

# Volume_Gap
new_set_df['Volume_Gap_LMH'] = pd.qcut(new_set_df['Volume_Gap'], 3, labels=["L", "M", "H"])
 
# Daily_Change
new_set_df['Daily_Change_LMH'] = pd.qcut(new_set_df['Daily_Change'], 3, labels=["L", "M", "H"])

# new set
new_set_df = new_set_df[["Sequence_ID", 
                         "Close_Date", 
                         "Close_Gap_LMH", 
                         "Volume_Gap_LMH", 
                         "Daily_Change_LMH", 
                         "Outcome_Next_Day_Direction"]]

new_set_df['Event_Pattern'] = new_set_df['Close_Gap_LMH'].astype(str) + new_set_df['Volume_Gap_LMH'].astype(str) + new_set_df['Daily_Change_LMH'].astype(str)

In [32]:
new_set_df.tail()

,Sequence_ID,Close_Date,Close_Gap_LMH,Volume_Gap_LMH,Daily_Change_LMH,Outcome_Next_Day_Direction,Event_Pattern
142,864624,2020-11-30,M,H,L,-5277039.0,MHL
143,864624,2020-11-30,M,H,H,-6432301.0,MHH
144,864624,2020-11-30,L,M,M,-10164782.0,LMM
145,864624,2020-11-30,H,L,H,-13041984.0,HLH
146,864624,2020-11-30,L,L,H,87103686.0,LLH

In [33]:
new_set_df['Outcome_Next_Day_Direction'].describe()

count    1.557608e+07
mean    -1.106790e+05
std      2.944470e+07
min     -3.226512e+07
25%     -1.281047e+07
50%     -9.291756e+06
75%     -6.504771e+06
max      1.399280e+08
Name: Outcome_Next_Day_Direction, dtype: float64

In [34]:
compressed_set = new_set_df.groupby(['Sequence_ID', 
                                     'Close_Date'])['Event_Pattern'].apply(
                                        lambda x: "{%s}" % ', '.join(x)).reset_index()

print(compressed_set.shape)
compressed_set.head()

(864625, 3)

   Sequence_ID  Close_Date                                      Event_Pattern
0            0  2020-12-02  {HHM, MMM, MHM, MHL, HMH, LLH, MLH, LHL, HLH, ...
1            1  2020-12-24  {LHL, HML, HHM, MHM, LMM, MLL, HLH, LHM, MHL, ...
2            2  2020-11-23  {HHH, LMM, HLM, HLL, HHL, HLL, MHL, HHH, LMM, ...
3            3  2020-12-10  {HHH, LHL, HMM, MLH, LLM, LHM, LMM, MML, HLL, ...
4            4  2020-11-20  {HLM, LLL, HHM, MMH, LHH, LHL, HMH, LLM, MLL, ...

In [35]:
compressed_outcomes = new_set_df.groupby(['Sequence_ID', 'Close_Date'])['Outcome_Next_Day_Direction'].mean()
compressed_outcomes = compressed_outcomes.to_frame().reset_index()
print(compressed_outcomes.shape)
compressed_outcomes.describe()

(864625, 3)

         Sequence_ID  Outcome_Next_Day_Direction
count  864625.000000                8.646250e+05
mean   432312.000000               -9.097539e+04
std    249595.882587                2.731467e+06
min         0.000000               -1.089279e+07
25%    216156.000000               -1.525839e+06
50%    432312.000000               -8.100200e+04
75%    648468.000000                1.245178e+06
max    864624.000000                1.793632e+07

In [36]:
compressed_set = pd.merge(compressed_set, compressed_outcomes, on= ['Sequence_ID', 'Close_Date'], how='inner')
print(compressed_set.shape)
compressed_set.head()

(864625, 4)

,Sequence_ID,Close_Date,Event_Pattern,Outcome_Next_Day_Direction
0,0,2020-12-02,"{HHM, MMM, MHM, MHL, HMH, LLH, MLH, LHL, HLH, ...",-5.163521e+06
1,1,2020-12-24,"{LHL, HML, HHM, MHM, LMM, MLL, HLH, LHM, MHL, ...",1.562613e+06
2,2,2020-11-23,"{HHH, LMM, HLM, HLL, HHL, HLL, MHL, HHH, LMM, ...",-2.249160e+05
3,3,2020-12-10,"{HHH, LHL, HMM, MLH, LLM, LHM, LMM, MML, HLL, ...",-1.926128e+05
4,4,2020-11-20,"{HLM, LLL, HHM, MMH, LHH, LHL, HMH, LLM, MLL, ...",1.389467e+06

In [37]:
compressed_set['Event_Pattern'] = [''.join(e.split()).replace('{','')
                                   .replace('}','') for e in compressed_set['Event_Pattern'].values]
compressed_set.head()

,Sequence_ID,Close_Date,Event_Pattern,Outcome_Next_Day_Direction
0,0,2020-12-02,"HHM,MMM,MHM,MHL,HMH,LLH,MLH,LHL,HLH,LLH,LMH,MM...",-5.163521e+06
1,1,2020-12-24,"LHL,HML,HHM,MHM,LMM,MLL,HLH,LHM,MHL,HHH,LHH,LM...",1.562613e+06
2,2,2020-11-23,"HHH,LMM,HLM,HLL,HHL,HLL,MHL,HHH,LMM,HLM,LLL,HH...",-2.249160e+05
3,3,2020-12-10,"HHH,LHL,HMM,MLH,LLM,LHM,LMM,MML,HLL,HLL,HLH,HL...",-1.926128e+05
4,4,2020-11-20,"HLM,LLL,HHM,MMH,LHH,LHL,HMH,LLM,MLL,MHL,HLH,MH...",1.389467e+06

In [38]:
compressed_set_validation = compressed_set[compressed_set['Close_Date'] >= datetime.datetime.now() 
                                           - datetime.timedelta(days=90)] # Sys.Date()-90 

compressed_set_validation.shape

TypeError: '>=' not supported between instances of 'str' and 'datetime.datetime'

In [ ]:
compressed_set = compressed_set[compressed_set['Close_Date'] < datetime.datetime.now() 
                                           - datetime.timedelta(days=90)]  
compressed_set.shape

In [ ]:
list(compressed_set)

In [ ]:
compressed_set = compressed_set[['Sequence_ID', 
                                 'Event_Pattern','Outcome_Next_Day_Direction']]
compressed_set_validation = compressed_set_validation[['Sequence_ID', 
                                                       'Event_Pattern','Outcome_Next_Day_Direction']]

In [ ]:
compressed_set['Outcome_Next_Day_Direction'].describe()

In [ ]:
print(len(compressed_set['Outcome_Next_Day_Direction']))
len(compressed_set[abs(compressed_set['Outcome_Next_Day_Direction']) > 10000000])

In [ ]:
print('all moves:', len(compressed_set))
compressed_set = compressed_set[abs(compressed_set['Outcome_Next_Day_Direction']) > 10000000]
compressed_set['Outcome_Next_Day_Direction'] = np.where((compressed_set['Outcome_Next_Day_Direction'] 
                                                         > 0), 1, 0)
compressed_set_validation['Outcome_Next_Day_Direction'] = np.where(
                                (compressed_set_validation['Outcome_Next_Day_Direction'] > 0), 1, 0)
print('big moves only:', len(compressed_set))

In [ ]:
compressed_set.head()

In [ ]:
compressed_set_pos = compressed_set[compressed_set['Outcome_Next_Day_Direction']==1][
                                                    ['Sequence_ID', 'Event_Pattern']]
print(compressed_set_pos.shape)
compressed_set_neg = compressed_set[compressed_set['Outcome_Next_Day_Direction']==0][
                                                    ['Sequence_ID', 'Event_Pattern']]
print(compressed_set_neg.shape)

In [ ]:
flat_list = [item.split(',') for item in compressed_set['Event_Pattern'].values ]
unique_patterns = ','.join(str(r) for v in flat_list for r in v)
unique_patterns = list(set(unique_patterns.split(',')))
len(unique_patterns)

In [ ]:
compressed_set['Outcome_Next_Day_Direction'].head()

In [ ]:
def build_transition_grid(compressed_grid, unique_patterns):
    # build the markov transition grid

    patterns = []
    counts = []
    for from_event in unique_patterns:

        # how many times 
        for to_event in unique_patterns:
            pattern = from_event + ',' + to_event # MMM,MlM

            ids_matches = compressed_grid[compressed_grid['Event_Pattern'].str.contains(pattern)]
            found = 0
            if len(ids_matches) > 0:
                Event_Pattern = '---'.join(ids_matches['Event_Pattern'].values)
                found = Event_Pattern.count(pattern)
            patterns.append(pattern)
            counts.append(found)

    # create to/from grid
    grid_Df = pd.DataFrame({'pairs':patterns, 'counts': counts})

    grid_Df['x'], grid_Df['y'] = grid_Df['pairs'].str.split(',', 1).str
    grid_Df.head()

    grid_Df = grid_Df.pivot(index='x', columns='y', values='counts')

    grid_Df.columns= [col for col in grid_Df.columns]
    del grid_Df.index.name

    # replace all NaN with zeros
    grid_Df.fillna(0, inplace=True)
    grid_Df.head()

    #grid_Df.rowSums(transition_dataframe) 
    grid_Df = grid_Df / grid_Df.sum(1)
    return (grid_Df)

In [ ]:
grid_pos = build_transition_grid(compressed_set_pos, unique_patterns) 
grid_neg = build_transition_grid(compressed_set_neg, unique_patterns)

In [ ]:
grid_neg.head()

In [ ]:
grid_pos.head()

In [ ]:
def safe_log(x,y):
   try:
      lg = np.log(x/y)
   except:
      lg = 0
   return lg

# predict on out of sample data
actual = []
predicted = []
for seq_id in compressed_set_validation['Sequence_ID'].values:
    patterns = compressed_set_validation[compressed_set_validation['Sequence_ID'] == seq_id]['Event_Pattern'].values[0].split(',')
    pos = []
    neg = []
    log_odds = []
    
    for id in range(0, len(patterns)-1):
        # get log odds
        # logOdds = log(tp(i,j) / tn(i,j)
        if (patterns[id] in list(grid_pos) and patterns[id+1] in list(grid_pos) and patterns[id] in list(grid_neg) and patterns[id+1] in list(grid_neg)):
                
            numerator = grid_pos[patterns[id]][patterns[id+1]]
            denominator = grid_neg[patterns[id]][patterns[id+1]]
            if (numerator == 0 and denominator == 0):
                log_value =0
            elif (denominator == 0):
                log_value = np.log(numerator / 0.00001)
            elif (numerator == 0):
                log_value = np.log(0.00001 / denominator)
            else:
                log_value = np.log(numerator/denominator)
        else:
            log_value = 0
        
        log_odds.append(log_value)
        
        pos.append(numerator)
        neg.append(denominator)
      
    print('outcome:', compressed_set_validation[compressed_set_validation['Sequence_ID']==seq_id]['Outcome_Next_Day_Direction'].values[0])
    print(sum(pos)/sum(neg))
    print(sum(log_odds))

    actual.append(compressed_set_validation[compressed_set_validation['Sequence_ID']==seq_id]['Outcome_Next_Day_Direction'].values[0])
    predicted.append(sum(log_odds))

from sklearn.metrics import confusion_matrix

confusion_matrix(actual, [1 if p > 0 else 0 for p in predicted])

In [ ]:
from sklearn.metrics import accuracy_score
score = accuracy_score(actual, [1 if p > 0 else 0 for p in predicted])
print('Accuracy:', round(score * 100,2), '%')

In [ ]:
import seaborn as sns
cm = confusion_matrix(actual, [1 if p > 0 else 0 for p in predicted])
fig, ax = plt.subplots(figsize=(5, 5))
sns.heatmap(cm, annot=True, ax = ax, fmt='g')

ax.set_title('Confusion Matrix') 
ax.set_xlabel('Predicted')
ax.set_ylabel('Actual')

ax.xaxis.set_ticklabels(['up day','down day'])
ax.yaxis.set_ticklabels(['up day','down day'])
ax.set_yticklabels(ax.get_yticklabels(), rotation = 0, fontsize = 8)
ax.set_xticklabels(ax.get_xticklabels(), rotation = 90, fontsize = 8)  
plt.show()