In [ ]:
import pandas as pd
import os
import glob
  

# use glob to get all the csv files 
# in the folder
path = r'C:\Users\lucki\WORK\OFFICE\TandM\VISE\Historical-Data\data\final_dump\Historical Data Companies\NSE'

In [ ]:
import os

# Getting the current work directory (cwd)
thisdir = os.getcwd()
dayPath = []
# r=root, d=directories, f = files
for r, d, f in os.walk(path):
    for file in f:
        if file.endswith("_day.csv"):
#             print(os.path.join(r, file))
            dayPath.append(os.path.join(r, file))
# dayPath[:100]

In [ ]:
# loop over the list of csv files
dfs = []
for f in dayPath[:100]:
      
    # read the csv file
    df = pd.read_csv(f)
      
    # print the location and filename
    print('Location:', f)
    print('File Name:', f.split("\\")[-1])
      
    # print the content
    print('Content:')
    display(df[['date', 'close']])
    dfs.append(df[['date', 'close']])
    print()

In [38]:
nse_companies = pd.read_csv(r'C:\Users\lucki\WORK\OFFICE\TandM\VISE\Historical-Data\data\final_dump\Companies + Indexes Tokens\NSE_final.csv')

nse_intruments_list = []

for k in range(len(nse_companies)):
    temp = [nse_companies['tradingsymbol'].tolist()[k], nse_companies['instrument_token'].tolist()[k]]
    nse_intruments_list.append(temp)

len(nse_intruments_list), nse_intruments_list[:5]

(1570,
 [['20MICRONS', 4331777],
  ['21STCENMGM', 1025],
  ['3IINFOTECH', 3014145],
  ['3MINDIA', 121345],
  ['3PLAND', 664321]])

In [ ]:
result = pd.concat(dfs, axis=1)

In [ ]:
result

In [ ]:
NSE = []

for k in nse_intruments_list:

In [46]:
msft = yf.Ticker("21STCENMGM.BO")

In [47]:
dfdd = msft.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2002-01-29,33.5234%,44.6979%,33.5234%,37.2483%,1000,0.0000%,0
2002-01-30,33.5234%,37.2483%,33.5234%,37.2483%,1700,0.0000%,0
2002-01-31,39.1107%,39.1107%,33.5234%,33.5234%,4600,0.0000%,0
2002-02-01,34.4547%,39.1107%,34.4547%,39.1107%,100,0.0000%,0
2002-02-04,32.5922%,46.5603%,32.5922%,41.9043%,4600,0.0000%,0
...,...,...,...,...,...,...,...
2021-06-07,1690.0000%,1690.0000%,1690.0000%,1690.0000%,621,0.0000%,0
2021-06-08,1720.0001%,1720.0001%,1720.0001%,1720.0001%,881,0.0000%,0
2021-06-09,1750.0000%,1750.0000%,1700.0000%,1750.0000%,7643,0.0000%,0
2021-06-10,1785.0000%,1785.0000%,1785.0000%,1785.0000%,602,0.0000%,0
2021-06-11,1820.0001%,1820.0001%,1785.0000%,1820.0001%,5663,0.0000%,0